spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/agentspace
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    com.agentspace: DEBUG

ai:
  gemini:
    api-key: ${GEMINI_API_KEY}
    model: gemini-2.5-flash

  huggingface:
    api-key: ${HUGGING_API_TOKEN}
    image-model: black-forest-labs/FLUX.1-schnell


application:
  name: AgentSpace AI
  version: 1.0.0
  base-url: http://localhost:8080

storage:
  generated-images: uploads/generated